type = "rust"
account_id = "12234"
route = "top-level"
kv_namespaces = [
    { binding = "FOO", id = "123456" },
    { binding = "BAR", id = "654321" }
]

[env.foo]
workers_dev = true
kv-namespaces = [
    { binding = "FOOFOO", id = "123456" },
    { binding = "FOOBAR", id = "654321" }
]

[env.bar]
account_id = "12345"
zone_id = "12345"
route = "bar-env"
kv-namespaces = [
    { binding = "BARFOO", id = "123456" },
    { binding = "BARBAR", id = "654321" }
]